### ISSUE TITLE
Deployment template validation failed

### ISSUE THREAD

**Issue by sanjayntms** [MicrosoftDocs/mslearn-n-tier-architecture#11]
Deployment template validation failed: 'The template variable 'deploymentUrl' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, parameters, mode, debugSetting, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'. (Code: InvalidTemplate)

**Comment by sanjayntms** [comment]
Hi,
I was trying to create using template option in Azure portal and getting errors
https://raw.githubusercontent.com/MicrosoftDocs/mslearn-n-tier-architecture/master/Deployment/azuredeploy.json

yours sincerely,Sanjay DubeyNTMS Training Institute
Whatsapp - 9702553000 
Web Site: ntmsworld.com

NTMS on Facebook
 

    On Friday, 18 January, 2019, 10:18:10 PM IST, Jason Boeshart <notifications@github.com> wrote:  
 
 This message is eligible for Automatic Cleanup! (notifications@github.com) Add cleanup rule | More info
 
@sanjayntms how were you deploying the template? This is intended to be deployed from this repo as part of the Microsoft Learn module that is referenced in the readme. Can you share more details on what you were doing when you received this error?

**Comment by jboeshart** [comment]
This template is currently configured in a way that doesn't work with the Portal, it uses the relative path of the template URL that is specified.  You'll need to deploy through the Azure CLI or through the cloud shell. Take a look at the Microsoft Learn module that this solution was designed for to see how it works. If you want to get it working in the portal, in the template editor change `deploymentUrl` to `https://raw.githubusercontent.com/MicrosoftDocs/mslearn-n-tier-architecture/master/Deployment/` so that the template dependencies can be found.
